import { WIZARD_SECTIONS } from "@prompter/shared";

function renderValue(value: unknown): string {
  if (value === null || value === undefined) return "_(not provided)_";
  if (typeof value === "string") return value;
  return "```json\n" + JSON.stringify(value, null, 2) + "\n```";
}

/**
 * Renders a project's TemplateResponse into a .md document following the
 * section structure of SaaS-Build-Prompt-Template.md. Per-section rendering
 * is JSON-based for now (structured data, not prose) -- a nicer bespoke
 * formatter per section is presentation polish for a later phase, not
 * required to prove the export/credit-consumption flow.
 */
export function renderTemplateMarkdown(
  projectName: string,
  templateResponse: Record<string, unknown>,
): string {
  const lines: string[] = [`# ${projectName}`, "", "_Generated by Prompter_", ""];

  for (const field of WIZARD_SECTIONS) {
    lines.push(`## ${field.section}. ${field.label}`, "", renderValue(templateResponse[field.id]), "");
  }

  return lines.join("\n");
}
