import { WIZARD_SECTIONS } from "@prompter/shared";

function escapeHtml(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function sectionHtml(value: unknown): string {
  if (value === null || value === undefined) return "<p><em>(not provided)</em></p>";
  if (typeof value === "string") return `<p>${escapeHtml(value)}</p>`;
  return `<pre>${escapeHtml(JSON.stringify(value, null, 2))}</pre>`;
}

/**
 * Shared HTML used both as the PDF source (rendered by Puppeteer) and,
 * potentially, a browser preview later -- one template instead of a
 * bespoke renderer per output format, per requirements-lock.md.
 */
export function renderTemplateHtml(
  projectName: string,
  templateResponse: Record<string, unknown>,
): string {
  const sections = WIZARD_SECTIONS.map(
    (field) =>
      `<h2>${field.section}. ${escapeHtml(field.label)}</h2>${sectionHtml(templateResponse[field.id])}`,
  ).join("\n");

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>${escapeHtml(projectName)}</title>
<style>
  body { font-family: -apple-system, Arial, sans-serif; max-width: 800px; margin: 40px auto; color: #1a1a1a; }
  h1 { font-size: 28px; }
  h2 { font-size: 18px; margin-top: 28px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
  pre { background: #f5f5f5; padding: 12px; overflow-x: auto; white-space: pre-wrap; }
</style>
</head>
<body>
  <h1>${escapeHtml(projectName)}</h1>
  <p><em>Generated by Prompter</em></p>
  ${sections}
</body>
</html>`;
}
