import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import { WIZARD_SECTIONS } from "@prompter/shared";

function sectionText(value: unknown): string {
  if (value === null || value === undefined) return "(not provided)";
  if (typeof value === "string") return value;
  return JSON.stringify(value, null, 2);
}

export async function renderTemplateDocx(
  projectName: string,
  templateResponse: Record<string, unknown>,
): Promise<Buffer> {
  const children: Paragraph[] = [
    new Paragraph({ text: projectName, heading: HeadingLevel.TITLE }),
    new Paragraph({ children: [new TextRun({ text: "Generated by Prompter", italics: true })] }),
  ];

  for (const field of WIZARD_SECTIONS) {
    children.push(
      new Paragraph({ text: `${field.section}. ${field.label}`, heading: HeadingLevel.HEADING_1 }),
      new Paragraph({ text: sectionText(templateResponse[field.id]) }),
    );
  }

  const doc = new Document({ sections: [{ children }] });
  return Packer.toBuffer(doc);
}
